services:
  nextapp:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy
    container_name: nextapp
    ports:
      - "3000:3000"
   # env_file:
    #  - .env.production
    # Alternative: use environment variables directly
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    #   - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    #   - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    